/**
 * Regenerates `src/lib/minecraft-version-manifest.ts` from Mojang's launcher
 * manifest.
 *
 *   pnpm mc:versions
 *
 * Run it whenever Mojang ships a release or snapshot, then commit the result.
 * Only `release` and `snapshot` entries are kept; the pre-1.0 `old_alpha` and
 * `old_beta` builds are not offered to uploaders.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const MANIFEST_URL =
  "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json";
const OUTPUT = fileURLToPath(
  new URL("../src/lib/minecraft-version-manifest.ts", import.meta.url)
);
const KEPT_KINDS = new Set(["release", "snapshot"]);

interface ManifestEntry {
  id: string;
  type: string;
}

interface Manifest {
  versions: ManifestEntry[];
}

const isManifest = (value: unknown): value is Manifest =>
  typeof value === "object" &&
  value !== null &&
  "versions" in value &&
  Array.isArray(value.versions);

const main = async () => {
  const response = await fetch(MANIFEST_URL, {
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) {
    throw new Error(`Mojang manifest request failed (${response.status}).`);
  }
  const manifest: unknown = await response.json();
  if (!isManifest(manifest)) {
    throw new Error("Mojang manifest has an unexpected shape.");
  }

  // Mojang lists versions newest first; keep that order.
  const rows: string[] = [];
  for (const entry of manifest.versions) {
    if (KEPT_KINDS.has(entry.type)) {
      const kind = entry.type === "release" ? "R" : "S";
      rows.push(`  [${JSON.stringify(entry.id)}, ${kind}],`);
    }
  }

  const source = `// Generated by \`pnpm mc:versions\` from Mojang's version manifest.
// Do not edit by hand; re-run the script to pick up new versions.

const R = "release";
const S = "snapshot";

export type MinecraftVersionKind = typeof R | typeof S;

/** Every release and snapshot, newest first: [id, kind]. */
export const MINECRAFT_VERSION_MANIFEST: readonly (readonly [
  id: string,
  kind: MinecraftVersionKind,
])[] = [
${rows.join("\n")}
];
`;

  await writeFile(OUTPUT, source);
  console.log(`Wrote ${rows.length} versions to ${OUTPUT}`);
};

await main();
