/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ModpacksIndexRouteImport } from './routes/modpacks.index'
import { Route as ModpacksSlugRouteImport } from './routes/modpacks.$slug'
import { Route as ModsIndexRouteImport } from './routes/mods.index'
import { Route as ModsSlugRouteImport } from './routes/mods.$slug'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsSlugRouteImport } from './routes/plugins.$slug'
import { Route as ResourcePacksIndexRouteImport } from './routes/resource-packs.index'
import { Route as ResourcePacksSlugRouteImport } from './routes/resource-packs.$slug'
import { Route as ServersIndexRouteImport } from './routes/servers.index'
import { Route as ServersSlugRouteImport } from './routes/servers.$slug'
import { Route as ShadersIndexRouteImport } from './routes/shaders.index'
import { Route as ShadersSlugRouteImport } from './routes/shaders.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAvatarAvatarIdRouteImport } from './routes/api/avatar.$avatarId'
import { Route as ApiDownloadFileIdRouteImport } from './routes/api/download.$fileId'
import { Route as ApiImageImageIdRouteImport } from './routes/api/image.$imageId'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as ModpacksSlugGalleryRouteImport } from './routes/modpacks.$slug.gallery'
import { Route as ModsSlugGalleryRouteImport } from './routes/mods.$slug.gallery'
import { Route as PluginsSlugGalleryRouteImport } from './routes/plugins.$slug.gallery'
import { Route as ResourcePacksSlugGalleryRouteImport } from './routes/resource-packs.$slug.gallery'
import { Route as ServersSlugGalleryRouteImport } from './routes/servers.$slug.gallery'
import { Route as ShadersSlugGalleryRouteImport } from './routes/shaders.$slug.gallery'
import { Route as AdminPostsPostIdEditRouteImport } from './routes/admin.posts.$postId.edit'
import { Route as ApiProjectsProjectIdImagesRouteImport } from './routes/api/projects.$projectId.images'
import { Route as ApiUsersMeAvatarRouteImport } from './routes/api/users.me.avatar'
import { Route as ApiProjectsProjectIdImagesImageIdRouteImport } from './routes/api/projects.$projectId.images.$imageId'
import { Route as ApiProjectsProjectIdVersionsVersionIdFilesRouteImport } from './routes/api/projects.$projectId.versions.$versionId.files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ModpacksIndexRoute = ModpacksIndexRouteImport.update({
  id: '/modpacks/',
  path: '/modpacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksSlugRoute = ModpacksSlugRouteImport.update({
  id: '/modpacks/$slug',
  path: '/modpacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsSlugRoute = ModsSlugRouteImport.update({
  id: '/mods/$slug',
  path: '/mods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePacksIndexRoute = ResourcePacksIndexRouteImport.update({
  id: '/resource-packs/',
  path: '/resource-packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePacksSlugRoute = ResourcePacksSlugRouteImport.update({
  id: '/resource-packs/$slug',
  path: '/resource-packs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersSlugRoute = ServersSlugRouteImport.update({
  id: '/servers/$slug',
  path: '/servers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersIndexRoute = ShadersIndexRouteImport.update({
  id: '/shaders/',
  path: '/shaders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersSlugRoute = ShadersSlugRouteImport.update({
  id: '/shaders/$slug',
  path: '/shaders/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarAvatarIdRoute = ApiAvatarAvatarIdRouteImport.update({
  id: '/api/avatar/$avatarId',
  path: '/api/avatar/$avatarId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFileIdRoute = ApiDownloadFileIdRouteImport.update({
  id: '/api/download/$fileId',
  path: '/api/download/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageImageIdRoute = ApiImageImageIdRouteImport.update({
  id: '/api/image/$imageId',
  path: '/api/image/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ModpacksSlugGalleryRoute = ModpacksSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ModpacksSlugRoute,
} as any)
const ModsSlugGalleryRoute = ModsSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ModsSlugRoute,
} as any)
const PluginsSlugGalleryRoute = PluginsSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PluginsSlugRoute,
} as any)
const ResourcePacksSlugGalleryRoute =
  ResourcePacksSlugGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => ResourcePacksSlugRoute,
  } as any)
const ServersSlugGalleryRoute = ServersSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ServersSlugRoute,
} as any)
const ShadersSlugGalleryRoute = ShadersSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ShadersSlugRoute,
} as any)
const AdminPostsPostIdEditRoute = AdminPostsPostIdEditRouteImport.update({
  id: '/$postId/edit',
  path: '/$postId/edit',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ApiProjectsProjectIdImagesRoute =
  ApiProjectsProjectIdImagesRouteImport.update({
    id: '/api/projects/$projectId/images',
    path: '/api/projects/$projectId/images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersMeAvatarRoute = ApiUsersMeAvatarRouteImport.update({
  id: '/api/users/me/avatar',
  path: '/api/users/me/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdImagesImageIdRoute =
  ApiProjectsProjectIdImagesImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => ApiProjectsProjectIdImagesRoute,
  } as any)
const ApiProjectsProjectIdVersionsVersionIdFilesRoute =
  ApiProjectsProjectIdVersionsVersionIdFilesRouteImport.update({
    id: '/api/projects/$projectId/versions/$versionId/files',
    path: '/api/projects/$projectId/versions/$versionId/files',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/welcome': typeof WelcomeRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRouteWithChildren
  '/mods/$slug': typeof ModsSlugRouteWithChildren
  '/plugins/$slug': typeof PluginsSlugRouteWithChildren
  '/resource-packs/$slug': typeof ResourcePacksSlugRouteWithChildren
  '/servers/$slug': typeof ServersSlugRouteWithChildren
  '/shaders/$slug': typeof ShadersSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/modpacks/': typeof ModpacksIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/resource-packs/': typeof ResourcePacksIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/shaders/': typeof ShadersIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$avatarId': typeof ApiAvatarAvatarIdRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/modpacks/$slug/gallery': typeof ModpacksSlugGalleryRoute
  '/mods/$slug/gallery': typeof ModsSlugGalleryRoute
  '/plugins/$slug/gallery': typeof PluginsSlugGalleryRoute
  '/resource-packs/$slug/gallery': typeof ResourcePacksSlugGalleryRoute
  '/servers/$slug/gallery': typeof ServersSlugGalleryRoute
  '/shaders/$slug/gallery': typeof ShadersSlugGalleryRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/projects/$projectId/images': typeof ApiProjectsProjectIdImagesRouteWithChildren
  '/api/users/me/avatar': typeof ApiUsersMeAvatarRoute
  '/api/projects/$projectId/images/$imageId': typeof ApiProjectsProjectIdImagesImageIdRoute
  '/api/projects/$projectId/versions/$versionId/files': typeof ApiProjectsProjectIdVersionsVersionIdFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/welcome': typeof WelcomeRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRouteWithChildren
  '/mods/$slug': typeof ModsSlugRouteWithChildren
  '/plugins/$slug': typeof PluginsSlugRouteWithChildren
  '/resource-packs/$slug': typeof ResourcePacksSlugRouteWithChildren
  '/servers/$slug': typeof ServersSlugRouteWithChildren
  '/shaders/$slug': typeof ShadersSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/modpacks': typeof ModpacksIndexRoute
  '/mods': typeof ModsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/resource-packs': typeof ResourcePacksIndexRoute
  '/servers': typeof ServersIndexRoute
  '/shaders': typeof ShadersIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$avatarId': typeof ApiAvatarAvatarIdRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/modpacks/$slug/gallery': typeof ModpacksSlugGalleryRoute
  '/mods/$slug/gallery': typeof ModsSlugGalleryRoute
  '/plugins/$slug/gallery': typeof PluginsSlugGalleryRoute
  '/resource-packs/$slug/gallery': typeof ResourcePacksSlugGalleryRoute
  '/servers/$slug/gallery': typeof ServersSlugGalleryRoute
  '/shaders/$slug/gallery': typeof ShadersSlugGalleryRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/projects/$projectId/images': typeof ApiProjectsProjectIdImagesRouteWithChildren
  '/api/users/me/avatar': typeof ApiUsersMeAvatarRoute
  '/api/projects/$projectId/images/$imageId': typeof ApiProjectsProjectIdImagesImageIdRoute
  '/api/projects/$projectId/versions/$versionId/files': typeof ApiProjectsProjectIdVersionsVersionIdFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/welcome': typeof WelcomeRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/modpacks/$slug': typeof ModpacksSlugRouteWithChildren
  '/mods/$slug': typeof ModsSlugRouteWithChildren
  '/plugins/$slug': typeof PluginsSlugRouteWithChildren
  '/resource-packs/$slug': typeof ResourcePacksSlugRouteWithChildren
  '/servers/$slug': typeof ServersSlugRouteWithChildren
  '/shaders/$slug': typeof ShadersSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/modpacks/': typeof ModpacksIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/resource-packs/': typeof ResourcePacksIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/shaders/': typeof ShadersIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$avatarId': typeof ApiAvatarAvatarIdRoute
  '/api/download/$fileId': typeof ApiDownloadFileIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/modpacks/$slug/gallery': typeof ModpacksSlugGalleryRoute
  '/mods/$slug/gallery': typeof ModsSlugGalleryRoute
  '/plugins/$slug/gallery': typeof PluginsSlugGalleryRoute
  '/resource-packs/$slug/gallery': typeof ResourcePacksSlugGalleryRoute
  '/servers/$slug/gallery': typeof ServersSlugGalleryRoute
  '/shaders/$slug/gallery': typeof ShadersSlugGalleryRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/projects/$projectId/images': typeof ApiProjectsProjectIdImagesRouteWithChildren
  '/api/users/me/avatar': typeof ApiUsersMeAvatarRoute
  '/api/projects/$projectId/images/$imageId': typeof ApiProjectsProjectIdImagesImageIdRoute
  '/api/projects/$projectId/versions/$versionId/files': typeof ApiProjectsProjectIdVersionsVersionIdFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/terms-of-use'
    | '/welcome'
    | '/admin/posts'
    | '/blog/$slug'
    | '/modpacks/$slug'
    | '/mods/$slug'
    | '/plugins/$slug'
    | '/resource-packs/$slug'
    | '/servers/$slug'
    | '/shaders/$slug'
    | '/u/$username'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/modpacks/'
    | '/mods/'
    | '/plugins/'
    | '/resource-packs/'
    | '/servers/'
    | '/shaders/'
    | '/admin/posts/new'
    | '/api/auth/$'
    | '/api/avatar/$avatarId'
    | '/api/download/$fileId'
    | '/api/image/$imageId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/modpacks/$slug/gallery'
    | '/mods/$slug/gallery'
    | '/plugins/$slug/gallery'
    | '/resource-packs/$slug/gallery'
    | '/servers/$slug/gallery'
    | '/shaders/$slug/gallery'
    | '/dashboard/projects/'
    | '/admin/posts/$postId/edit'
    | '/api/projects/$projectId/images'
    | '/api/users/me/avatar'
    | '/api/projects/$projectId/images/$imageId'
    | '/api/projects/$projectId/versions/$versionId/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/disclaimer'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/terms-of-use'
    | '/welcome'
    | '/admin/posts'
    | '/blog/$slug'
    | '/modpacks/$slug'
    | '/mods/$slug'
    | '/plugins/$slug'
    | '/resource-packs/$slug'
    | '/servers/$slug'
    | '/shaders/$slug'
    | '/u/$username'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/modpacks'
    | '/mods'
    | '/plugins'
    | '/resource-packs'
    | '/servers'
    | '/shaders'
    | '/admin/posts/new'
    | '/api/auth/$'
    | '/api/avatar/$avatarId'
    | '/api/download/$fileId'
    | '/api/image/$imageId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/modpacks/$slug/gallery'
    | '/mods/$slug/gallery'
    | '/plugins/$slug/gallery'
    | '/resource-packs/$slug/gallery'
    | '/servers/$slug/gallery'
    | '/shaders/$slug/gallery'
    | '/dashboard/projects'
    | '/admin/posts/$postId/edit'
    | '/api/projects/$projectId/images'
    | '/api/users/me/avatar'
    | '/api/projects/$projectId/images/$imageId'
    | '/api/projects/$projectId/versions/$versionId/files'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/terms-of-use'
    | '/welcome'
    | '/admin/posts'
    | '/blog/$slug'
    | '/modpacks/$slug'
    | '/mods/$slug'
    | '/plugins/$slug'
    | '/resource-packs/$slug'
    | '/servers/$slug'
    | '/shaders/$slug'
    | '/u/$username'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/modpacks/'
    | '/mods/'
    | '/plugins/'
    | '/resource-packs/'
    | '/servers/'
    | '/shaders/'
    | '/admin/posts/new'
    | '/api/auth/$'
    | '/api/avatar/$avatarId'
    | '/api/download/$fileId'
    | '/api/image/$imageId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/modpacks/$slug/gallery'
    | '/mods/$slug/gallery'
    | '/plugins/$slug/gallery'
    | '/resource-packs/$slug/gallery'
    | '/servers/$slug/gallery'
    | '/shaders/$slug/gallery'
    | '/dashboard/projects/'
    | '/admin/posts/$postId/edit'
    | '/api/projects/$projectId/images'
    | '/api/users/me/avatar'
    | '/api/projects/$projectId/images/$imageId'
    | '/api/projects/$projectId/versions/$versionId/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  WelcomeRoute: typeof WelcomeRoute
  ModpacksSlugRoute: typeof ModpacksSlugRouteWithChildren
  ModsSlugRoute: typeof ModsSlugRouteWithChildren
  PluginsSlugRoute: typeof PluginsSlugRouteWithChildren
  ResourcePacksSlugRoute: typeof ResourcePacksSlugRouteWithChildren
  ServersSlugRoute: typeof ServersSlugRouteWithChildren
  ShadersSlugRoute: typeof ShadersSlugRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
  ModpacksIndexRoute: typeof ModpacksIndexRoute
  ModsIndexRoute: typeof ModsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  ResourcePacksIndexRoute: typeof ResourcePacksIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  ShadersIndexRoute: typeof ShadersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarAvatarIdRoute: typeof ApiAvatarAvatarIdRoute
  ApiDownloadFileIdRoute: typeof ApiDownloadFileIdRoute
  ApiImageImageIdRoute: typeof ApiImageImageIdRoute
  ApiProjectsProjectIdImagesRoute: typeof ApiProjectsProjectIdImagesRouteWithChildren
  ApiUsersMeAvatarRoute: typeof ApiUsersMeAvatarRoute
  ApiProjectsProjectIdVersionsVersionIdFilesRoute: typeof ApiProjectsProjectIdVersionsVersionIdFilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/modpacks/': {
      id: '/modpacks/'
      path: '/modpacks'
      fullPath: '/modpacks/'
      preLoaderRoute: typeof ModpacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks/$slug': {
      id: '/modpacks/$slug'
      path: '/modpacks/$slug'
      fullPath: '/modpacks/$slug'
      preLoaderRoute: typeof ModpacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods/'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$slug': {
      id: '/mods/$slug'
      path: '/mods/$slug'
      fullPath: '/mods/$slug'
      preLoaderRoute: typeof ModsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-packs/': {
      id: '/resource-packs/'
      path: '/resource-packs'
      fullPath: '/resource-packs/'
      preLoaderRoute: typeof ResourcePacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-packs/$slug': {
      id: '/resource-packs/$slug'
      path: '/resource-packs/$slug'
      fullPath: '/resource-packs/$slug'
      preLoaderRoute: typeof ResourcePacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$slug': {
      id: '/servers/$slug'
      path: '/servers/$slug'
      fullPath: '/servers/$slug'
      preLoaderRoute: typeof ServersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders/': {
      id: '/shaders/'
      path: '/shaders'
      fullPath: '/shaders/'
      preLoaderRoute: typeof ShadersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders/$slug': {
      id: '/shaders/$slug'
      path: '/shaders/$slug'
      fullPath: '/shaders/$slug'
      preLoaderRoute: typeof ShadersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$avatarId': {
      id: '/api/avatar/$avatarId'
      path: '/api/avatar/$avatarId'
      fullPath: '/api/avatar/$avatarId'
      preLoaderRoute: typeof ApiAvatarAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$fileId': {
      id: '/api/download/$fileId'
      path: '/api/download/$fileId'
      fullPath: '/api/download/$fileId'
      preLoaderRoute: typeof ApiDownloadFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$imageId': {
      id: '/api/image/$imageId'
      path: '/api/image/$imageId'
      fullPath: '/api/image/$imageId'
      preLoaderRoute: typeof ApiImageImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/modpacks/$slug/gallery': {
      id: '/modpacks/$slug/gallery'
      path: '/gallery'
      fullPath: '/modpacks/$slug/gallery'
      preLoaderRoute: typeof ModpacksSlugGalleryRouteImport
      parentRoute: typeof ModpacksSlugRoute
    }
    '/mods/$slug/gallery': {
      id: '/mods/$slug/gallery'
      path: '/gallery'
      fullPath: '/mods/$slug/gallery'
      preLoaderRoute: typeof ModsSlugGalleryRouteImport
      parentRoute: typeof ModsSlugRoute
    }
    '/plugins/$slug/gallery': {
      id: '/plugins/$slug/gallery'
      path: '/gallery'
      fullPath: '/plugins/$slug/gallery'
      preLoaderRoute: typeof PluginsSlugGalleryRouteImport
      parentRoute: typeof PluginsSlugRoute
    }
    '/resource-packs/$slug/gallery': {
      id: '/resource-packs/$slug/gallery'
      path: '/gallery'
      fullPath: '/resource-packs/$slug/gallery'
      preLoaderRoute: typeof ResourcePacksSlugGalleryRouteImport
      parentRoute: typeof ResourcePacksSlugRoute
    }
    '/servers/$slug/gallery': {
      id: '/servers/$slug/gallery'
      path: '/gallery'
      fullPath: '/servers/$slug/gallery'
      preLoaderRoute: typeof ServersSlugGalleryRouteImport
      parentRoute: typeof ServersSlugRoute
    }
    '/shaders/$slug/gallery': {
      id: '/shaders/$slug/gallery'
      path: '/gallery'
      fullPath: '/shaders/$slug/gallery'
      preLoaderRoute: typeof ShadersSlugGalleryRouteImport
      parentRoute: typeof ShadersSlugRoute
    }
    '/admin/posts/$postId/edit': {
      id: '/admin/posts/$postId/edit'
      path: '/$postId/edit'
      fullPath: '/admin/posts/$postId/edit'
      preLoaderRoute: typeof AdminPostsPostIdEditRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/api/projects/$projectId/images': {
      id: '/api/projects/$projectId/images'
      path: '/api/projects/$projectId/images'
      fullPath: '/api/projects/$projectId/images'
      preLoaderRoute: typeof ApiProjectsProjectIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me/avatar': {
      id: '/api/users/me/avatar'
      path: '/api/users/me/avatar'
      fullPath: '/api/users/me/avatar'
      preLoaderRoute: typeof ApiUsersMeAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/images/$imageId': {
      id: '/api/projects/$projectId/images/$imageId'
      path: '/$imageId'
      fullPath: '/api/projects/$projectId/images/$imageId'
      preLoaderRoute: typeof ApiProjectsProjectIdImagesImageIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdImagesRoute
    }
    '/api/projects/$projectId/versions/$versionId/files': {
      id: '/api/projects/$projectId/versions/$versionId/files'
      path: '/api/projects/$projectId/versions/$versionId/files'
      fullPath: '/api/projects/$projectId/versions/$versionId/files'
      preLoaderRoute: typeof ApiProjectsProjectIdVersionsVersionIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsPostIdEditRoute: typeof AdminPostsPostIdEditRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsPostIdEditRoute: AdminPostsPostIdEditRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ModpacksSlugRouteChildren {
  ModpacksSlugGalleryRoute: typeof ModpacksSlugGalleryRoute
}

const ModpacksSlugRouteChildren: ModpacksSlugRouteChildren = {
  ModpacksSlugGalleryRoute: ModpacksSlugGalleryRoute,
}

const ModpacksSlugRouteWithChildren = ModpacksSlugRoute._addFileChildren(
  ModpacksSlugRouteChildren,
)

interface ModsSlugRouteChildren {
  ModsSlugGalleryRoute: typeof ModsSlugGalleryRoute
}

const ModsSlugRouteChildren: ModsSlugRouteChildren = {
  ModsSlugGalleryRoute: ModsSlugGalleryRoute,
}

const ModsSlugRouteWithChildren = ModsSlugRoute._addFileChildren(
  ModsSlugRouteChildren,
)

interface PluginsSlugRouteChildren {
  PluginsSlugGalleryRoute: typeof PluginsSlugGalleryRoute
}

const PluginsSlugRouteChildren: PluginsSlugRouteChildren = {
  PluginsSlugGalleryRoute: PluginsSlugGalleryRoute,
}

const PluginsSlugRouteWithChildren = PluginsSlugRoute._addFileChildren(
  PluginsSlugRouteChildren,
)

interface ResourcePacksSlugRouteChildren {
  ResourcePacksSlugGalleryRoute: typeof ResourcePacksSlugGalleryRoute
}

const ResourcePacksSlugRouteChildren: ResourcePacksSlugRouteChildren = {
  ResourcePacksSlugGalleryRoute: ResourcePacksSlugGalleryRoute,
}

const ResourcePacksSlugRouteWithChildren =
  ResourcePacksSlugRoute._addFileChildren(ResourcePacksSlugRouteChildren)

interface ServersSlugRouteChildren {
  ServersSlugGalleryRoute: typeof ServersSlugGalleryRoute
}

const ServersSlugRouteChildren: ServersSlugRouteChildren = {
  ServersSlugGalleryRoute: ServersSlugGalleryRoute,
}

const ServersSlugRouteWithChildren = ServersSlugRoute._addFileChildren(
  ServersSlugRouteChildren,
)

interface ShadersSlugRouteChildren {
  ShadersSlugGalleryRoute: typeof ShadersSlugGalleryRoute
}

const ShadersSlugRouteChildren: ShadersSlugRouteChildren = {
  ShadersSlugGalleryRoute: ShadersSlugGalleryRoute,
}

const ShadersSlugRouteWithChildren = ShadersSlugRoute._addFileChildren(
  ShadersSlugRouteChildren,
)

interface ApiProjectsProjectIdImagesRouteChildren {
  ApiProjectsProjectIdImagesImageIdRoute: typeof ApiProjectsProjectIdImagesImageIdRoute
}

const ApiProjectsProjectIdImagesRouteChildren: ApiProjectsProjectIdImagesRouteChildren =
  {
    ApiProjectsProjectIdImagesImageIdRoute:
      ApiProjectsProjectIdImagesImageIdRoute,
  }

const ApiProjectsProjectIdImagesRouteWithChildren =
  ApiProjectsProjectIdImagesRoute._addFileChildren(
    ApiProjectsProjectIdImagesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  WelcomeRoute: WelcomeRoute,
  ModpacksSlugRoute: ModpacksSlugRouteWithChildren,
  ModsSlugRoute: ModsSlugRouteWithChildren,
  PluginsSlugRoute: PluginsSlugRouteWithChildren,
  ResourcePacksSlugRoute: ResourcePacksSlugRouteWithChildren,
  ServersSlugRoute: ServersSlugRouteWithChildren,
  ShadersSlugRoute: ShadersSlugRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
  ModpacksIndexRoute: ModpacksIndexRoute,
  ModsIndexRoute: ModsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  ResourcePacksIndexRoute: ResourcePacksIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  ShadersIndexRoute: ShadersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarAvatarIdRoute: ApiAvatarAvatarIdRoute,
  ApiDownloadFileIdRoute: ApiDownloadFileIdRoute,
  ApiImageImageIdRoute: ApiImageImageIdRoute,
  ApiProjectsProjectIdImagesRoute: ApiProjectsProjectIdImagesRouteWithChildren,
  ApiUsersMeAvatarRoute: ApiUsersMeAvatarRoute,
  ApiProjectsProjectIdVersionsVersionIdFilesRoute:
    ApiProjectsProjectIdVersionsVersionIdFilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
